### ISSUE TITLE
Incorrect floating point test assertion

### ISSUE THREAD

**Issue by David-Hari** [mch/python-ant#7]
https://github.com/mch/python-ant/blob/b6e8a7afb9000c2ac4fdc84c5fb2c8d818322a83/tests/ant/plus/test_heartrate.py#L260

Testing for specific times is not a good idea, but I don't understand why you didn't at least use `assertAlmostEqual` more often.
When I run the tests, they fail with assertion errors like:
> AssertionError: 333 != 333.0078125
> AssertionError: 1.9649999999999999 != 1.9658203125

**Comment by mch** [comment]
The tests are not time dependent as they don't depend on the wall clock time, only on the data provided by the test itself. They are testing floating point computations, so they should be asserted with `assertAlmostEqual`.

**Comment by David-Hari** [comment]
Ah, ok. Can you change them all to `assertAlmostEqual` then?

**Comment by mch** [comment]
I've pushed a commit that switches the floating point comparisons to `assertAlmostEqual`. Let me know if you still have test failures.

**Comment by David-Hari** [comment]
It still doesn't work, because according to `assertAlmostEqual`, which defaults to 7 decimal places, 333 isn't even remotely close to 333.0078125. They differ after just 3 dp.
I'm not sure how you managed to get it to work.

**Comment by David-Hari** [comment]
Sorry, ignore that above comment. I think I may have messed something up in the calculation.

**Comment by David-Hari** [comment]
I fixed this in my pull request.
